### ISSUE TITLE
Is this production-ready?

### ISSUE THREAD

**Issue by dipeti** [chenggangpro/reactive-lock#1]
Hi mate, 

I've come across your code whilst searching for a solution that implements distributed locking with Reactor. I am truly impressed by how elegant a solution you've created. It seems to fit my problem perfectly, I am just wondering if you had a chance to run the code in a production environment. If so, have you encountered any issues worth sharing here?

Thanks

**Comment by chenggangpro** [comment]
Hi mate,
Thanks for your approval.
I actually use this code in a real business scenario of a production environment.We have encountered some problems in the process of using it, and I apologize for not updating it to the GitHub repository yet because I am too busy to update it.When utilizing it, we found :
* `DefaultReactiveLock` still performs well in our practical use.
* `RedisReactiveLock` in our actual usage, we found that the current code of GitHub repository does not check the ownership of the `LOCK` when unlocking, which can be a problem here. (Will update it up in a few days.)

There are a few things to note about this `Reactive Lock` implementation:
* `DefaultReactiveLock` and `RedisReactiveLock` are both implemented based on the spin lock implementation.
* `RedisReactiveLock` uses Redis Lua scripts to ensure atomicity through the `SETNX` command and `PEXPIRE` command, so the problem is still about lock expiration time.

I plan to sync our production code and add `JMH Benchmark` test cases in a few days.I'll keep you informed of this issue when the update is done.

**Comment by dipeti** [comment]
Thanks for the prompt and detailed explanation bud, I'll be back in a couple weeks to check out the suggested improvements.

**Comment by chenggangpro** [comment]
Hi @dipeti ,
I've synced the production code to the GitHub repository and added the benchmark tests based on `JMH`. You may check out the commit log to catch up the changes.
Hope this repository helps.

**Comment by chenggangpro** [comment]
close this, because no response
